#!/bin/bash

echo -e '* XENIUM PROGRAMMER TOOLCHAIN INSTALLATION *\n'

# general pre-reqs
echo -e '-------------------------------------------'
echo -e '\n  INSTALLING UPDATES AND REQUIREMENTS\n'
echo -e '-------------------------------------------'
sudo apt -y update
sudo apt -y install build-essential wiringpi git cmake

# make and install xenium-flash to bin
echo -e '----------------------------------------------------------'
echo -e '\n BUILDING AND INSTALLING XENIUM JTAG AND FLASH TOOLS\n'
echo -e '----------------------------------------------------------'
cd xenium-flash
make
sudo cp bin/xenium-jtag /usr/local/bin
sudo cp bin/xenium-flash /usr/local/bin
cd ..

chmod +x xenium-programmer

echo -e '\n** INSTALL COMPLETE **\n'

echo -e '\nTo program your Xenium, just run:\n\t ./xenium-programmer xenium-bin/xenium_blue.bin \n'


