#!/bin/bash

echo -e '* XENIUM PROGRAMMER TOOLCHAIN INSTALLATION *\n'

# general pre-reqs
echo -e '-------------------------------------------'
echo -e '\n  INSTALLING UPDATES AND REQUIREMENTS\n'
echo -e '-------------------------------------------'
sudo apt -y update
sudo apt -y install build-essential libusb-dev libftdi-dev libgpiod-dev wiringpi git cmake

#install XC3SPROG
echo -e '-----------------------'
echo -e '\n INSTALLING XC3SPROG\n'
echo -e '-----------------------'
git clone https://github.com/matrix-io/xc3sprog 
mkdir xc3sprog/build
cd xc3sprog/build
cmake .. 
make
sudo make install
cd ../..

# make and install xenium-flash to bin
echo -e '-----------------------------------------------'
echo -e '\n BUILDING AND INSTALLING XENIUM-FLASH TOOL\n'
echo -e '-----------------------------------------------'
cd xenium-flash
make
cp bin/xenium-flash /usr/local/bin
cd ..

chmod +x xenium-programmer

echo -e '\n** INSTALL COMPLETE **\n'



