#!/bin/bash

echo -e '\n OPEN XENIUM PROGRAMMER'
echo -e '***************************\n'

if [ $# -ne 1 ] ; then
  echo -e 'Error: Xenium Flash Image file not supplied! \n'
  echo -e '\tUsage: xenium-programmer [XENIUM_IMAGE]'
  echo -e '\tExample: xenium-programmer xenium-bin/xenium_blue.bin \n'
  exit 1
fi

# Paths to default JED files
XENIUM_OS=$1
XENIUM_JED=xenium-bin/openxenium.jed
FLASH_JED=xenium-bin/xeniumflash.jed

# Program the Xilinx CPLD with BitBus2Flash firmware.
echo -e '--------------------------------------'
echo -e 'PROGRAMMING XILINX CPLD: BITBUS BRIDGE'
echo -e '--------------------------------------'
xenium-jtag $FLASH_JED
if [ $? -ne 0 ]
then
  echo "ERROR Programming the Xilinx CPLD: " $FLASH_JED
  echo "Please double check your JTAG connection and wires!" 
  exit $?
fi

# Send XeniumOS Image to Flash Memory via bitbus bridge
echo -e '-----------------------------'
echo -e 'PROGRAMMING FLASH : XENIUM OS'
echo -e '-----------------------------'
xenium-flash/bin/xenium-flash $XENIUM_OS
if [ $? -ne 0 ]
then
  echo "ERROR Loading XeniumOS into OpenXenium Flash memory!"
  echo "Please double check your LPC Header connection and wires!" 
  exit $?
fi

# Program the Xilinx CPLD with OpenXenium Firmware
echo -e '---------------------------------------------'
echo -e 'PROGRAMMING XILINX CPLD: OPEN XENIUM FIRMWARE'
echo -e '---------------------------------------------'
xenium-jtag $XENIUM_JED
if [ $? -ne 0 ]
then
  echo "ERROR Programming the Xilinx CPLD: " $XENIUM_JED
  echo "Please double check your JTAG connection and wires!" 
  exit $?
fi

